import asyncio
import sys

from hireai.core.agents.ceo_agent import CEOAgent

# --- Mock Classes to Simulate External Frameworks ---
class MockLangChainChatOpenAI:
    def invoke(self, prompt: str):
        return "[LangChain Output] Data processed by ChatOpenAI."

class MockAutoGenConversableAgent:
    def generate_reply(self, messages):
        return "[AutoGen Output] Reply generated by ConversableAgent."

class MockCrewAIAgent:
    def execute_task(self, task):
        return "[CrewAI Output] Task completed by CrewAI Agent."
# --------------------------------------------------

async def main():
    print("=====================================================")
    print("=== HireAI Cross-Framework Fusion Test (3-Majors) ===")
    print("=====================================================\n")
    
    # 1. Instantiate external framework objects
    langchain_brain = MockLangChainChatOpenAI()
    autogen_worker = MockAutoGenConversableAgent()
    crewai_worker = MockCrewAIAgent()
    
    # 2. Initialize CEOAgent with LangChain as its main brain
    print("--- [STEP 1] Inject LangChain as CEO's Brain ---")
    ceo = CEOAgent(llm_object=langchain_brain)
    
    # 3. Spawn SubAgents but outsource them to AutoGen and CrewAI
    print("\n--- [STEP 2] CEO hires AutoGen and CrewAI as Sub-Contractors ---")
    autogen_sub_id = await ceo.spawn_agent(role="Data Analyst (AutoGen)", external_agent=autogen_worker)
    crewai_sub_id = await ceo.spawn_agent(role="Code Writer (CrewAI)", external_agent=crewai_worker)
    
    # 4. Delegate tasks
    print("\n--- [STEP 3] CEO Delegates Tasks to Sub-Contractors ---")
    autogen_result = await ceo.delegate_task(autogen_sub_id, "Analyze the market data.", {"data": "..."})
    crewai_result = await ceo.delegate_task(crewai_sub_id, "Write a script based on analysis.", {"analysis": autogen_result})
    
    # 5. Output Results
    print("\n--- [FINAL FUSION RESULT] ---")
    print(f"Data Analyst Result : {autogen_result}")
    print(f"Code Writer Result  : {crewai_result}")
    
    # 6. Dissolve
    print("\n--- [STEP 4] CEO Dissolves Sub-Contractors ---")
    await ceo.dissolve_agent(autogen_sub_id)
    await ceo.dissolve_agent(crewai_sub_id)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
